// <auto-generated />
namespace StockManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Upd_MIO_clas1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upd_MIO_clas1));
        
        string IMigrationMetadata.Id
        {
            get { return "201705240937387_Upd_MIO_clas1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
