// <auto-generated />
namespace StockManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Up_m_c2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Up_m_c2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705242314434_Up_m_c2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
