// <auto-generated />
namespace StockManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Up2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Up2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705231422575_Up2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
