//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Entities.Resources.Material {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Material {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Material() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockManagement.Entities.Resources.Material.Material", typeof(Material).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition.
        /// </summary>
        internal static string Acquisition {
            get {
                return ResourceManager.GetString("Acquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Informations.
        /// </summary>
        internal static string AcquisitionInformations {
            get {
                return ResourceManager.GetString("AcquisitionInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Value.
        /// </summary>
        internal static string AcquisitionValue {
            get {
                return ResourceManager.GetString("AcquisitionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition Value Exist.
        /// </summary>
        internal static string AcquisitionValueExist {
            get {
                return ResourceManager.GetString("AcquisitionValueExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery.
        /// </summary>
        internal static string delivery {
            get {
                return ResourceManager.GetString("delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimension.
        /// </summary>
        internal static string dimension {
            get {
                return ResourceManager.GetString("dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INN Number.
        /// </summary>
        internal static string INN_Number {
            get {
                return ResourceManager.GetString("INN_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Informations.
        /// </summary>
        internal static string InventoryInformations {
            get {
                return ResourceManager.GetString("InventoryInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Number.
        /// </summary>
        internal static string InventoryNumber {
            get {
                return ResourceManager.GetString("InventoryNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to material Category.
        /// </summary>
        internal static string materialCategory {
            get {
                return ResourceManager.GetString("materialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Situation.
        /// </summary>
        internal static string MaterialSituation {
            get {
                return ResourceManager.GetString("MaterialSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        internal static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical State.
        /// </summary>
        internal static string PhysicalState {
            get {
                return ResourceManager.GetString("PhysicalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        internal static string PluralName {
            get {
                return ResourceManager.GetString("PluralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie Number.
        /// </summary>
        internal static string SerieNumber {
            get {
                return ResourceManager.GetString("SerieNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string SingularName {
            get {
                return ResourceManager.GetString("SingularName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Existence.
        /// </summary>
        internal static string StockExistence {
            get {
                return ResourceManager.GetString("StockExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Service Date.
        /// </summary>
        internal static string UpdateServiceDate {
            get {
                return ResourceManager.GetString("UpdateServiceDate", resourceCulture);
            }
        }
    }
}
